repos:
# Pre-commit offical hooks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
# Pylint
-   repo: https://github.com/pycqa/pylint
    rev: 'v2.16.1'
    hooks:
    - id: pylint
      additional_dependencies: [pandas, click, pygithub]
      args: [ "--rcfile", "pylintrc" ]
# Isort
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
# Jupyter Notebook clear output
-   repo: local
    hooks:
    - id: jupyter-nb-clear-output
      name: jupyter-nb-clear-output
      files: \.ipynb$
      stages: [commit]
      language: system
      entry: jupyter nbconvert --clear-output --inplace
