on:
  issue_comment:
    types: [created, deleted]

env:
  CI_REPO_DIR: Selection-of-CI-tools

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }} && contains(github.event.comment.body, '/test')
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v2
      with:
        repository: JJSveding/Selection-of-CI-tools
        token: ${{ secrets.MY_SECRET_CI_TOOLS }}

    - name: Hello world
      run: |
        echo $PWD
        ls
        python ${{ env.CI_REPO_DIR }}/src/my-bot.py --pr-number "$_PR_NUMBER"
      shell: sh
      env:
        credentials: ${{ secrets.MY_SECRET_CI_TOOLS }}
