on:
  issue_comment:
    types: [created, deleted]

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }} && contains(github.event.comment.body, '/test')
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v2
      with:
        repository: JJSveding/Selection-of-CI-tools
        token: ${{ secrets.MY_SECRET_CI_TOOLS }}
        path: Selection-of-CI-tools

    - name: Hello world
      run: |
        echo 'Hello world'
        python src/my-bot.py --pr-number "$_PR_NUMBER"
      shell: sh
      env:
      credentials: ${{ secrets.MY_SECRET_CI_TOOLS }}
