on:
  issue_comment:
    types: [created, deleted]

env:
  CI_REPO_DIR: Selection-of-CI-tools
  PR_NUMBER: ${{ github.event.number }}

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }} && contains(github.event.comment.body, '/test')
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v2
      with:
        repository: JJSveding/Selection-of-CI-tools
        token: ${{ secrets.MY_SECRET_CI_TOOLS }}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Print comment
      run: |
        echo $_PR_NUMBER
        python src/cli.py print-changed-costs --pr-number "$PR_NUMBER"
      shell: sh
      env:
        credentials: ${{ secrets.MY_SECRET_CI_TOOLS }}
