name: pull request comment
on:
  issue_comment:
    types: [created, edited, deleted]
jobs:
job01:
  if: contains(github.event.comment.html_url, '/hello')
  runs-on: [ubuntu-latest]
  steps:
    - name: Test trigger
      run: |
        echo say hello
