name: pull request comment
jobs:
  sampleJob:
    name: Sample Job
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '/test')"
    steps:
    - name: Test trigger
      run: |
        echo say hello
