name: pull request comment
on:
  issue_comment:
    types: [created, edited, deleted]
jobs:
  sampleJob:
    name: Sample Job
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '/test')"
    steps:
    - name: Test trigger
      env:
        credentials: ${{ secrets.MY_SECRET_CI_TOOLS }}
      run: |
        python src/my-bot.py --pr-number "$_PR_NUMBER"
